name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          cd main-chat
          npm install --legacy-peer-deps
      - name: Run tests
        run: |
          cd main-chat
          npm test -- --watchAll=false
      - name: Build app
        run: |
          cd main-chat
          npm run build
      - name: Deploy to VPS via SSH
        if: github.ref == 'refs/heads/main'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "main-chat/build/*"
          target: ${{ secrets.VPS_PATH }}
          strip_components: 2
